### ISSUE TITLE
Composer update issue with Laravel 5.1

### ISSUE THREAD

**Issue by FoxRocks76** [kylekatarnls/laravel-carbon-2#5]
I just discovered this package and was trying to install it on an older Laravel project, but I'm getting the following error:

Problem 1
    - Root composer.json requires nesbot/carbon 2.27.0 as 1.39.0 -> satisfiable by nesbot/carbon[2.27.0].
    - laravel/framework[v5.1.0, ..., v5.1.46] require symfony/translation 2.7.* -> satisfiable by symfony/translation[v2.7.0, ..., v2.7.51].
    - Conclusion: don't install symfony/translation v2.7.51 (conflict analysis result)
    - Root composer.json requires laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, ..., v5.1.46].

Here is my composer.json file:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "barryvdh/laravel-ide-helper": "^2.1",
        "laravelcollective/html": "5.1.*",
        "kylekatarnls/laravel-carbon-2": "^1.0.0",
        "nesbot/carbon": "2.27.0 as 1.39.0",
        "intervention/image": "^2.3",
        "fzaninotto/faker": "^1.7",
        "bugsnag/bugsnag-laravel": "^2.0",
        "silber/bouncer": " v1.0.0-rc.4",
        "doctrine/dbal": "v2.9"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "pams\\": "app/"
        },
		"files": [
			"app/Helpers/PamsHelper.php",
            "app/Helpers/ListMaker.php"
		]
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

Sorry, I'm not sure how to properly format this code snippet to look correct.

**Comment by kylekatarnls** [comment]
Hello, you're on Laravel 5.1 which is very old and and have the following security issues:
https://packagist.org/packages/laravel/framework/advisories?version=1306238

So first of all, please consider to upgrade to >=6.20.42 (check red warning⚠️ on https://packagist.org/packages/laravel/framework in the version list) which already support Carbon 2 natively and has all those known security issues fixed.

This package (kylekatarnls/laravel-carbon-2) is only provided as a transitional work-around to upgrade.

In your particular situation, you're blocked because of the version of symfony/translation 2.7 (which last patch is more than 4 years old). Carbon 2 requires at least 3.4 and won't work with a lower version.

That's the point with keeping old stacks, it's a bottomless pit. Many packages have crossed dependencies so trying to upgrade some packages but keep very old ones in the same project always ends with tears. And not upgrading anything ends with having security breaches and being unable to install some new features.

By comparison to other choices, upgrading the whole framework is actually the easier and safer way.

**Comment by FoxRocks76** [comment]
Thank you for the prompt reply. Unfortunately this is a legacy project that doesn't qualify for an update, as version 2 of the platform is currently in production. I was just trying to add in a small feature request thinking it wouldn't be a big deal, but we can do without if it's not possible to implement this package. Cheers!
